---
title: "'Exit Try' は、'Try' ステートメント内部でのみ使用できます"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 5280b041f1219ab9577e684c0814c13821ed9de0
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84397117"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' は、'Try' ステートメント内部でのみ使用できます
`Exit Try` は、 `Try` ブロック ステートメント内でのみ使用できます。 冗長な `Exit Try` ステートメントがあるか、または `Exit Try` ステートメントが対応する `Try` ブロックの境界の外側にあります。  
  
 **エラー ID:** BC30393  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. 不要な `Exit Try` ステートメントを見つけて削除します。  
  
2. ステートメントを `Exit Try` コード内の適切な場所に移動します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
