---
title: "'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ab300d332dd82870901aec9bd57d8d5d8081a533
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403772"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません
コード内で `Catch` ステートメントが、 `Finally` ステートメント ブロックの末尾の `Try` の後にあります。 `Catch` は `Try...Catch...Finally` ステートメント ブロック内に置く必要があります。  
  
 **エラー ID:** BC30379  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. `Catch` ステートメントをコード内の適切な場所に移動します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
