---
title: "'<labelname>' は、このステートメントを含まない 'Try'、'Catch' または 'Finally' ステートメントの内側にあるため、'GoTo <labelname>' は有効ではありません。"
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 54fbd1852d60605290bef7816b05f7b9ffc8c673
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84412547"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>'\<labelname>' は、このステートメントを含まない 'Try'、'Catch' または 'Finally' ステートメントの内側にあるため、'GoTo \<labelname>' は有効ではありません。
`Try...Catch...Finally` ブロック内に分岐することはできません。  
  
 **エラー ID:** BC30754  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- `Try...Catch...Finally` ブロックの前にラベルが配置されるように、コードを再構成します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
