---
title: "'Finally' を 'Try' ステートメントの外に置くことはできません。"
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 60f02c9000e99c6f1b91fb5f0e2929c4e696e549
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403733"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>'Finally' を 'Try' ステートメントの外に置くことはできません。
`Finally` は `Try...Catch...Finally` ブロックを終了するために使用します。そのため、ブロックの最後で 1 回のみ出現できます。 不要な `Finally`ステートメントがあるか、または `Finally` ステートメントが、対応する `Try` ブロックの境界の外側にあります。  
  
 **エラー ID:** BC30382  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. 不要な `Finally` ステートメントを見つけて削除します。  
  
2. `Finally` ステートメントをコード内の適切な場所に移動します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
