---
title: 型 '<typename>' は、'System.Exception'、または 'System.Exception' から継承するクラスではないため、'Catch' でキャッチできません。
ms.date: 07/20/2015
f1_keywords:
- vbc30392
- bc30392
helpviewer_keywords:
- BC30392
ms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803
ms.openlocfilehash: 778591653948b64b1f6336bad6f48d520b22e51c
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84397130"
---
# <a name="catch-cannot-catch-type-typename-because-it-is-not-systemexception-or-a-class-that-inherits-from-systemexception"></a>型 '\<typename>' は、'System.Exception'、または 'System.Exception' から継承するクラスではないため、'Catch' でキャッチできません。
`Catch` は例外のみをインターセプトできますが、例外から派生していないものを検出しようとしました。  
  
 **エラー ID:** BC30392  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. `Catch` ステートメントを削除するか、または `Catch` の対象を実際の例外に変更します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
